config/routes.rb
Rails.application.routes.draw do
	root :to => "invoice_bills#index"
  resources :collections
  resources :invoice_bills
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :reference
end

app/models/invoice_bill.rb
class InvoiceBill < ApplicationRecord
  belongs_to :reference
  has_many :collections, through: :reference

  def self.status(status)
  	case status
  	  when "pending"
         InvoiceBill.includes(:collections).where(collections: { id: nil })
      when "complete"
         InvoiceBill.joins(:collections)
    end   	
  		
  end	
end

app/models/reference.rb
class Reference < ApplicationRecord
has_one :invoice_bill
has_many :collections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
    @reference = Reference.find(params[:reference_id])
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:amount, :date, :reference_id)
    end
end

app/controllers/invoice_bills_controller.rb
class InvoiceBillsController < ApplicationController
  before_action :set_invoice_bill, only: [:show, :edit, :update, :destroy]
  #extend CodeInvoice

  # GET /invoice_bills
  # GET /invoice_bills.json
  def index
    if params[:status].present?
      @invoice_bills = InvoiceBill.status(params[:status])
    else
      @invoice_bills = InvoiceBill.all
    end  
  end

  # GET /invoice_bills/1
  # GET /invoice_bills/1.json
  def show
    @collections = @invoice_bill.reference.collections
  end

  # GET /invoice_bills/new
  def new
    @invoice_bill = InvoiceBill.new
  end

  # GET /invoice_bills/1/edit
  def edit
  end

  # POST /invoice_bills
  # POST /invoice_bills.json
  def create
    @invoice_bill = InvoiceBill.new(invoice_bill_params.merge(reference_id: Reference.create(name: params[:invoice_bill][:reference_id]).id))
    respond_to do |format|
      if @invoice_bill.save
        format.html { redirect_to @invoice_bill, notice: 'Invoice bill was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_bill }
      else
        format.html { render :new }
        format.json { render json: @invoice_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_bills/1
  # PATCH/PUT /invoice_bills/1.json
  def update
    respond_to do |format|
      if @invoice_bill.update(invoice_bill_params)
        format.html { redirect_to @invoice_bill, notice: 'Invoice bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_bill }
      else
        format.html { render :edit }
        format.json { render json: @invoice_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_bills/1
  # DELETE /invoice_bills/1.json
  def destroy
    @invoice_bill.destroy
    respond_to do |format|
      format.html { redirect_to invoice_bills_url, notice: 'Invoice bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_bill
      @invoice_bill = InvoiceBill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_bill_params
      params.require(:invoice_bill).permit( :date, :customer, :brand_manager, :narration, :amount, :total_collection, :balance_due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/invoice_bills_helper.rb
module InvoiceBillsHelper
	def total_collections(reference_id)
    Reference.find(reference_id).collections.pluck(:amount).sum
  end	

  def balance_due(total_amount,reference_id)
    total_amount + Reference.find(reference_id).collections.pluck(:amount).sum
  end	
end

app/views/collections/_form.html.erb
<%= form_with(model: collection, local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :collection_amount %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :collection_date %>
  </div>

  <div class="field">
    <%#= form.label :reference_id %>
    <%= form.hidden_field :reference_id, id: :collection_reference_id,value: @reference.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
      <th>Reference</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.amount %></td>
        <td><%= collection.date %></td>
        <td><%= collection.reference.name %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @collection.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @collection.date %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @collection.reference.name %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>

app/views/invoice_bills/_form.html.erb
<%= form_with(model: invoice_bill, local: true) do |form| %>
  <% if invoice_bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_bill.errors.count, "error") %> prohibited this invoice_bill from being saved:</h2>

      <ul>
      <% invoice_bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reference_id %>
    <%= form.text_field :reference_id, id: :invoice_bill_reference_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :invoice_bill_date %>
  </div>

  <div class="field">
    <%= form.label :customer %>
    <%= form.text_field :customer, id: :invoice_bill_customer %>
  </div>

  <div class="field">
    <%= form.label :brand_manager %>
    <%= form.text_field :brand_manager, id: :invoice_bill_brand_manager %>
  </div>

  <div class="field">
    <%= form.label :narration %>
    <%= form.text_field :narration, id: :invoice_bill_narration %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :invoice_bill_amount %>
  </div>

  <!-- <div class="field">
    <%#= form.label :total_collection %>
    <%#= form.text_field :total_collection, id: :invoice_bill_total_collection %>
  </div>

  <div class="field">
    <%#= form.label :balance_due %>
    <%#= form.text_field :balance_due, id: :invoice_bill_balance_due %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_bills/edit.html.erb
<h1>Editing Invoice Bill</h1>

<%= render 'form', invoice_bill: @invoice_bill %>

<%= link_to 'Show', @invoice_bill %> |
<%= link_to 'Back', invoice_bills_path %>

app/views/invoice_bills/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Add New Bill', new_invoice_bill_path() %>
<%pending_color = params[:status] == "pending" ? "color: red;" : ""%>
<%complete_color = params[:status] == "complete" ? "color: red;" : ""%>
<%= link_to 'Show Pending Bill ', invoice_bills_path({status: "pending"}),style: pending_color %>
<%= link_to 'Show collected Bill', invoice_bills_path({status: "complete"}),style: complete_color %>
<h1>Invoice Bills</h1>

<table>
  <thead>
    <tr>
      <th>Reference</th>
      <th>Invoice Date</th>
      <th>Customer</th>
      <th>Brand manager</th>
      <th>Narration</th>
      <th>Amount</th>
      <th>Total collection</th>
      <th>Balance due</th>
      <th>Add Collections</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_bills.each do |invoice_bill| %>
      <tr>
        <td><%= invoice_bill.reference.name %></td>
        <td><%= invoice_bill.date %></td>
        <td><%= invoice_bill.customer %></td>
        <td><%= invoice_bill.brand_manager %></td>
        <td><%= invoice_bill.narration %></td>
        <td><%= amount = invoice_bill.amount %></td>
        <td><%= total_bal = total_collections(invoice_bill.reference.id).abs %></td>
        <td><%= amount - total_bal %></td>
        <td><%= link_to 'New Collection', new_collection_path({reference_id: invoice_bill.reference_id}) %></td>
        <td><%= link_to 'Show', invoice_bill %></td>
        <td><%= link_to 'Destroy', invoice_bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/invoice_bills/new.html.erb
<h1>New Invoice Bill</h1>

<%= render 'form', invoice_bill: @invoice_bill%>

<%= link_to 'Back', invoice_bills_path %>

app/views/invoice_bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reference:</strong>
  <%= @invoice_bill.reference.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invoice_bill.date %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @invoice_bill.customer %>
</p>

<p>
  <strong>Brand manager:</strong>
  <%= @invoice_bill.brand_manager %>
</p>

<p>
  <strong>Narration:</strong>
  <%= @invoice_bill.narration %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @invoice_bill.amount %>
</p>

<p>
  <strong>Total collection:</strong>
  <%= @invoice_bill.total_collection %>
</p>

<p>
  <strong>Balance due:</strong>
  <%= @invoice_bill.balance_due %>
</p>

<%= link_to 'Edit', edit_invoice_bill_path(@invoice_bill) %> |
<%= link_to 'Back', invoice_bills_path %>


<table border="2">
  <thead>
    <th>Reference</th>
    <th>Collections Date</th>
  </thead>
  <body>
    <%@collections.map do |coll|%>
      <tr>
        <td><%= coll.reference.name%></td>
        <td><%= coll.date%></td>
        <!-- <td></td> -->
      </tr>
    <%end%>
  </body>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>